spring.application.name=careerflow

spring.datasource.url=jdbc:postgresql://localhost:5432/core-db
spring.datasource.username=postgres
spring.datasource.password=@Tul1885

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true